# Generated by Django 5.2.4 on 2025-07-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_comment_active_alter_category_slug_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.TextField(blank=True, verbose_name='پاسخ دیدگاه'),
        ),
    ]
