# Generated by Django 5.2.4 on 2025-07-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_alter_post_created_at_alter_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='send_notification',
            field=models.BooleanField(default=False, verbose_name='ارسال نوتیفیکیشن'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', 'ip_address'], name='Post_like_post_id_9ba3e6_idx'),
        ),
    ]
