# Generated by Django 5.2.4 on 2025-07-25 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_post_send_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_description',
            field=models.CharField(default=' ', max_length=200, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_keywords',
            field=models.CharField(default=' ', max_length=100, verbose_name='کلمات کلیدی'),
        ),
    ]
