# Generated by Django 5.2.4 on 2025-07-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_post_author_post_seo_description_post_seo_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_description',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
