# Generated by Django 5.2.4 on 2025-07-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_category_meta_description_tag_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='privte',
            field=models.BooleanField(default=False, verbose_name=' نظرخصوصی '),
        ),
    ]
