# Generated by Django 5.2.4 on 2025-09-10 08:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_comment_privte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='پاسخ دیدگاه'),
        ),
    ]
