# Generated by Django 5.2.4 on 2025-07-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'تنظیمات درباره من', 'verbose_name_plural': 'درباره من'},
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='توضیحات درباره من'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان صفحه'),
        ),
    ]
