# Generated by Django 5.2.4 on 2025-07-04 08:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0002_alter_about_options_alter_about_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150, verbose_name='نام سایت')),
                ('site_url', models.URLField(blank=True, null=True, verbose_name='آدرس سایت')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='لوگو سایت')),
                ('site_icon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='آیکون سایت (favicon)')),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات سئو')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, null=True, verbose_name='کلمات کلیدی سئو')),
                ('meta_author', models.CharField(blank=True, max_length=150, null=True, verbose_name='نویسنده سئو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن تنظیمات')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
    ]
