# Generated by Django 5.2.4 on 2025-07-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0003_sitesetting_alter_about_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': ' عمومی', 'verbose_name_plural': ' عمومی'},
        ),
    ]
