# Generated by Django 5.2.4 on 2025-07-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0004_alter_sitesetting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('link', models.URLField(verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'لینک های دوستان ',
                'verbose_name_plural': 'لینک های دوستان',
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='settings/', verbose_name='موسیقی سایت'),
        ),
    ]
