# Generated by Django 5.2.4 on 2025-07-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0006_notificationsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='music_cover',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='کاور موسیقی سایت'),
        ),
    ]
