# Generated by Django 5.2.4 on 2025-07-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0007_sitesetting_music_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='email_admin',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل مدیر سایت'),
        ),
    ]
