# Generated by Django 5.2.4 on 2025-07-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0008_sitesetting_email_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='music_artist',
            field=models.CharField(default='', max_length=150, verbose_name='نام خواننده موسیقی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='music_title',
            field=models.CharField(default='as', max_length=150, verbose_name='عنوان موسیقی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_author',
            field=models.CharField(max_length=150, verbose_name='نویسنده سئو'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_description',
            field=models.CharField(default='', max_length=300, verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_keywords',
            field=models.CharField(max_length=300, verbose_name='کلمات کلیدی سئو'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='music',
            field=models.FileField(upload_to='settings/', verbose_name='موسیقی سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='music_cover',
            field=models.ImageField(upload_to='settings/', verbose_name='کاور موسیقی سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_url',
            field=models.URLField(verbose_name='آدرس سایت'),
        ),
    ]
