# Generated by Django 5.2.4 on 2025-07-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0009_sitesetting_music_artist_sitesetting_music_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsubscription',
            name='name',
            field=models.CharField(default='ناشناس', max_length=150, verbose_name='نام'),
        ),
    ]
