# Generated by Django 5.2.4 on 2025-09-10 09:33

import Gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='لوکیشن')),
                ('sender_name', models.CharField(max_length=100, verbose_name='نام فرستنده')),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل فرستنده')),
                ('photo', models.ImageField(upload_to=Gallery.models.image_upload_path, validators=[Gallery.models.validate_image_size], verbose_name='عکس')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'آیتم گالری',
                'verbose_name_plural': 'آیتم\u200cهای گالری',
                'ordering': ['-created_at'],
            },
        ),
    ]
