# Generated by Django 5.2.4 on 2025-07-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0005_links_sitesetting_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_info', models.JSONField(verbose_name='اطلاعات نوتیفیکیشن')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آی\u200cپی کاربر')),
                ('browser_info', models.CharField(max_length=255, verbose_name='مدل مرورگر')),
                ('device_info', models.CharField(max_length=255, verbose_name='مدل دیوایس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'مشترکان ',
                'verbose_name_plural': 'مشترکان',
            },
        ),
    ]
